import { useEffect, useState } from "react";
import { api } from "../api";

const statuses = ["", "VERIFIED", "NEEDS_REVIEW", "OUTSIDE_STORE_AREA", "STORE_LOCATION_NOT_AVAILABLE", "LOW_GPS_ACCURACY"];
const label: Record<string, string> = { VERIFIED: "Verified", NEEDS_REVIEW: "Needs review", OUTSIDE_STORE_AREA: "Outside store area", STORE_LOCATION_NOT_AVAILABLE: "Store location unavailable", LOW_GPS_ACCURACY: "Low GPS accuracy" };

export default function Visits() {
  const [status, setStatus] = useState("");
  const [visits, setVisits] = useState<any[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [filters, setFilters] = useState({ retailerId: "", salespersonId: "", territory: "", from: "", to: "" });
  const load = () => api.visits({ status, ...filters }).then((result) => setVisits(result.visits ?? [])).catch((err) => setError(err instanceof Error ? err.message : "Could not load visits"));
  // Filters are intentionally applied only when the user presses “Apply filters”.
  // oxlint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [status]);
  return <div><h1 className="page-title">Sales visits</h1><p className="page-sub">Review foreground check-ins without treating GPS as proof of intent.</p>{error && <div className="banner error">{error}</div>}<div className="tabs">{statuses.map((item) => <button key={item || "all"} className={`tab ${status === item ? "active" : ""}`} onClick={() => setStatus(item)}>{item ? label[item] : "All visits"}</button>)}</div><div className="card"><div className="form-grid"><div className="field"><label>Retailer ID</label><input value={filters.retailerId} onChange={(e) => setFilters({ ...filters, retailerId: e.target.value })} /></div><div className="field"><label>Salesperson ID</label><input value={filters.salespersonId} onChange={(e) => setFilters({ ...filters, salespersonId: e.target.value })} /></div><div className="field"><label>Territory</label><input value={filters.territory} onChange={(e) => setFilters({ ...filters, territory: e.target.value })} placeholder="Pune North" /></div><div className="field"><label>From</label><input type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /></div><div className="field"><label>To</label><input type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /></div></div><button onClick={() => void load()}>Apply filters</button></div><div className="card" style={{ padding: 0 }}>{visits.length === 0 ? <div className="empty-state">No visits in this filter.</div> : <table><thead><tr><th>Salesperson</th><th>Retailer</th><th>Check in</th><th>Check out</th><th>Distance</th><th>Status</th></tr></thead><tbody>{visits.map((visit) => <tr key={visit.id}><td>{visit.salesperson?.name ?? visit.salespersonId}</td><td>{visit.retailer?.name ?? visit.retailerId}</td><td>{new Date(visit.checkedInAt).toLocaleString("en-IN")}</td><td>{visit.checkedOutAt ? new Date(visit.checkedOutAt).toLocaleString("en-IN") : "—"}</td><td>{visit.distanceFromStoreMeters == null ? "—" : `${Math.round(Number(visit.distanceFromStoreMeters))} m`}</td><td><span className={`pill ${visit.verificationStatus === "VERIFIED" ? "confirmed" : visit.verificationStatus === "OUTSIDE_STORE_AREA" ? "rejected" : "placed"}`}>{label[visit.verificationStatus] ?? visit.verificationStatus}</span>{visit.checkedInAt && visit.checkedOutAt ? <div className="small muted">{Math.round((new Date(visit.checkedOutAt).getTime() - new Date(visit.checkedInAt).getTime()) / 60000)} min</div> : null}</td></tr>)}</tbody></table>}</div></div>;
}
